---
title: "cpm y filtraje"
author: "Marina Ballesteros"
date: "6/6/2020"
output: html_document
---


Generación de las cuentas por millón de los genes.

```{r}
# Obtain CPMs
myCPM <- cpm(counts_30)
# Have a look at the output
head(myCPM)
```

Por regla general, se puede elegir un buen umbral identificando el CPM que corresponde a un conteo de 10, que en este caso es aproximadamente 0,15.

```{r}
# Which values in myCPM are greater than 0.5?
thresh <- myCPM > 0.15
# This produces a logical matrix with TRUEs and FALSEs
head(thresh)
```

```{r}
# Summary of how many TRUEs there are in each row
table(rowSums(thresh))
# we would like to keep genes that have at least 2 TRUES in each row of thresh
keep <- rowSums(thresh) >= 10
# Subset the rows of countdata to keep the more highly expressed genes
counts.keep <- counts_30[keep,]
summary(keep)
dim(counts.keep)
```

```{r}
# Let's have a look and see whether our threshold of 0.5 does indeed correspond to a count of about 10-15
# We will look at the first sample
plot(myCPM[,1],counts_30[,1])
# Let us limit the x and y-axis so we can actually look to see what is happening at the smaller counts
plot(myCPM[,1],counts_30[,1],ylim=c(0,50),xlim=c(0,3))
# Add a vertical line at 0.15 CPM
abline(v=0.15)
```

Convertir los genes filtrados en una DEGList

```{r}
dgeObj <- DGEList(counts.keep, group = group)
# have a look at dgeObj
dgeObj
# See what slots are stored in dgeObj
names(dgeObj)
# Library size information is stored in the samples slot
dgeObj$samples
```
